version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: puppeteer-scraper-api-dev
    container_name: puppeteer-scraper-api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=debug
      - USE_MOCK_BROWSER=false
      - BROWSERBASE_API_KEY=your_browserbase_key
      - BROWSERBASE_PROJECT_ID=your_project_id
      - API_KEYS=test-key-1,test-key-2
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
