FROM node:16-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source
COPY . .

# Create logs directory
RUN mkdir -p logs

# Expose the application port
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"] 